[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iscstack"
version = "1.0.5"
description = "ISCStack - The Intelligent Systems Control Stack - Authority is a Runtime Property"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name="Ibrahim Salama"}]
dependencies = []

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
include = ["iscstack", "iscstack.*"]
